.c8rc, .circleci/config.yml, .gitignore, build.js, metrics.yaml, package-lock.json, package.json, pings.yaml, src/chromium/interfaces/contextMenus.js, src/chromium/interfaces/listeners.js, src/chromium/manifest.json, src/chromium/pages/welcomePage/index.html, src/firefox/interfaces/listeners.js, src/firefox/manifest.json, src/firefox/pages/welcomePage/index.html, src/firefox/pages/welcomePage/script.js, src/shared/backgroundScripts/background.js, src/shared/backgroundScripts/contextMenus.js, src/shared/backgroundScripts/hotkeys.js, src/shared/backgroundScripts/listeners.js, src/shared/backgroundScripts/telemetry.js, src/shared/pages/myExternalSites/index.html, test/setup.test.js, test/shared/backgroundScripts/listeners.test.js, test/shared/backgroundScripts/telemetry.test.js, webpack.config.mjs
Add glean, the glean build process, and implement each of the required metrics.
=> Add glean with metrics

README.md, build.js, src/chromium/interfaces/contextMenus.js, src/chromium/interfaces/getters.js, src/chromium/interfaces/launchBrowser.js, src/chromium/interfaces/listeners.js, src/chromium/manifest.json, src/chromium/pages/welcomePage/script.js, src/firefox/api.js, src/firefox/interfaces/contextMenus.js, src/firefox/interfaces/getters.js, src/firefox/interfaces/launchBrowser.js, src/firefox/interfaces/listeners.js, src/firefox/manifest.json, src/firefox/pages/welcomePage/script.js, src/shared/backgroundScripts/actionButton.js, src/shared/backgroundScripts/autoRedirect.js, src/shared/backgroundScripts/contextMenus.js, src/shared/backgroundScripts/getters.js, src/shared/backgroundScripts/hotkeys.js, src/shared/backgroundScripts/listeners.js, src/shared/backgroundScripts/telemetry.js, src/shared/backgroundScripts/validTab.js, test/setup.test.js, test/shared/backgroundScripts/contextMenus.test.js
Write the readme, add docstrings, change up code for readability
=> Readme + Docs + refactoring

src/_locales/en/messages.json, src/chromium/manifest.json, src/firefox/api.js, src/firefox/manifest.json, src/firefox/schema.json, src/shared/backgroundScripts/contextMenus.js, src/shared/backgroundScripts/hotkeys.js, src/shared/backgroundScripts/telemetry.js, src/shared/pages/welcomePage/browserList.js, src/shared/pages/welcomePage/localization.js, src/shared/pages/welcomePage/script.js
1. Updating strings in the manifest to relate to the spec
2. Auto choose safari or edge if no default is set
3. shortcut to the firefox addons page from welcome page
4. fix action context menu differenced for mv2 and mv3
=> Small spec changes

README.md, package.json, src/firefox/interfaces/contextMenus.js, src/shared/backgroundScripts/contextMenus.js
Edit typos, change the package to private, edit the readme to use firefox dev instead of beta.
Review comments:
1. https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468653834
2. https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468657166
3. https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468907211
4. https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468903280
=> Code Review: Typos, Small changes

src/_locales/en/messages.json
- Add descriptions for objects with variables
- Fix the apostrophes
- rename Firefox Launch to Launch in Firefox (temporary)
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1467861148
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1467865161
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1467870909
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1467872601
=> Code Review: Basic locales changes

src/_locales/en/messages.json
Manual for now. Forced prettier and lint checking will come in a later PR.
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1467861148
=> Code Review: Format locale messages json

src/_locales/en/messages.json, src/shared/pages/welcomePage/localization.js
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1467868333
=> Code Review: Use <a> tags instead of {LinkStart} and {LinkEnd}

README.md, src/chromium/interfaces/contextMenus.js, src/chromium/interfaces/launchBrowser.js, src/chromium/interfaces/listeners.js, src/chromium/manifest.json, src/firefox/api.js, src/firefox/interfaces/listeners.js, src/firefox/manifest.json, src/shared/backgroundScripts/hotkeys.js, src/shared/backgroundScripts/telemetry.js, src/shared/pages/welcomePage/localization.js, test/chromium/interfaces/launchBrowser.test.js
Various small changes listed in the below comments
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468914009
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468912062
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468902381
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468905820
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468904073
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468878978
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468680658
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468877906
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468667448
=> Code Review: Many more tiny changes

.eslintrc.json, .gitignore, README.md, jest.config.js, package-lock.json, package.json, src/chromium/interfaces/getters.js, src/firefox/api.js, src/firefox/interfaces/launchBrowser.js, src/shared/backgroundScripts/getters.js, src/shared/backgroundScripts/telemetry.js, src/shared/pages/welcomePage/browserList.js
Adds instructions to download the firefox source code and develop the experimental apis using it. Adds in eslint rules for api.
=> Experimental APIs: Instructions

src/firefox/api.js
Take the helper functions outside of the experimental api namespace. Add docstrings to each as well (many will change in future patches)
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468879648
=> Code Review: Reformat the API 

src/shared/backgroundScripts/getters.js, src/shared/pages/welcomePage/script.js
Code review comments:
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468936100
=> Code review: default telemetry to false

src/shared/pages/welcomePage/localization.js, src/shared/pages/welcomePage/script.js
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468936758
=> Code Review: addons:// and chrome:// shortcuts link handling for no shortcuts found

src/shared/backgroundScripts/listeners.js, test/setup.test.js, test/shared/backgroundScripts/listeners.test.js
Code review comments:
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468908722
=> Code Review: Use session storage for context menu init

src/chromium/interfaces/contextMenus.js, src/shared/backgroundScripts/contextMenus.js, test/chromium/interfaces/contextMenus.test.js, test/shared/backgroundScripts/contextMenus.test.js
Code review:
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468908722
=> add a callback to suppress duplicate ID logspam in chrome

src/_locales/en/messages.json, src/shared/pages/welcomePage/script.js
also make casing of Firefox Private Browsing consistent
- https://github.com/mozilla/firefox-launch/pull/18/files#r1472359832
=> use specific l10n string for shortcuts to firefox private

src/firefox/api.js
Adds in some small changes to the api.js file like better variable names and documentation.
I'm investigating the TODO with nipun.
Code Review:
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468895582
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468892624
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468883423
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468883276
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468901530
=> Code Review: Small api changes with docs

metrics.yaml, src/_locales/en/messages.json, src/chromium/manifest.json, src/firefox/manifest.json, src/shared/backgroundScripts/getters.js, src/shared/backgroundScripts/telemetry.js, src/shared/pages/welcomePage/script.js
Also, add in the proper listener for events in the welcome page private checkbox.
=> Use event pings instead of metrics in telemetry

README.md, src/shared/pages/welcomePage/index.html, src/shared/pages/welcomePage/script.js, src/shared/pages/welcomePage/style.css
Fixes: #55 , #56 , #66 , #67 , #57 , #68 
Adds tabindex field to suitable elements, adds aria fields to sliders, adds alt text to images.
With the styling of the sliders, the screen reader could not read the state of the checkbox.
=> Screen reader + keyboard navigation improvements

src/shared/backgroundScripts/listeners.js, src/shared/pages/welcomePage/localization.js, test/setup.test.js, test/shared/backgroundScripts/listeners.test.js
These links will eventually point to the proper location.
=> Change temporary links + uninstall URL

src/_locales/en/messages.json, src/chromium/manifest.json, src/firefox/manifest.json, src/shared/pages/welcomePage/index.html, src/shared/pages/welcomePage/localization.js, src/shared/pages/welcomePage/script.js, src/shared/pages/welcomePage/style.css
Changes the name to "Firefox Bridge (Beta)". Adds a tab title specific localization tag. Removes the mobile specific formatting.
=> Welcome Page string changes

.github/CODEOWNERS
Adding Codeowners and a l10n reviewer group to review string changes.
=> Create CODEOWNERS for l10n string review
