mozilla-extensions/firefox-bridge

src/_locales/en/messages.json, src/background.js, src/manifest.json, test/backgroundScripts/background.test.js, test/setup.js
Fixes [Jira issue](https://mozilla-hub.atlassian.net/browse/AMO-131)
Hotkeys are assigned on installation of the extension. This change attempts to assign `ctrl/cmd+shift+f/p` to the proper launch mode, but if they have been taken by another program, does not set the hotkey. In this case, the user has to navigate to `chrome://extensions/shortcuts` or equivalent to set the desired hotkeys.
Also reorganize background.js.
=> Add hotkeys to launch firefox modes

src/firefox/api.js, src/firefox/schema.json, src/shared/pages/welcomePage/localization.js
This patch renames openPrivilegedUrl to openShortcutsPage and removes the url parameter since it is only used to launch one URL. Handling the other references to "addons://" will be done in a future patch related to https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468662523 and the special case
A future patch can rid this requirement altogether with the implementation of this bugzilla ticket: [Make extension shortcut management page accessible by a link/URL for a WebExtension](https://bugzilla.mozilla.org/show_bug.cgi?id=1538451)
- https://github.com/mozilla/firefox-launch/pull/18#discussion_r1468664417
=> Code Review: Rename openPrivilegedUrl to openShortcutsPage

src/chromium/interfaces/getters.js, test/chromium/interfaces/contextMenus.test.js, test/chromium/interfaces/getters.test.js, test/chromium/interfaces/launchBrowser.test.js, test/chromium/interfaces/listeners.test.js, test/firefox/interfaces/contextMenus.test.js, test/firefox/interfaces/getters.test.js, test/firefox/interfaces/launchBrowser.test.js, test/setup.test.js, test/shared/backgroundScripts/actionButton.test.js, test/shared/backgroundScripts/contextMenus.test.js
Update the isFirefoxInstalled getter to be clear why it is always true and to use session storage. Update tests to support this change, including having a better storage mocking system.
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468671709
=> Code Review: isFirefoxInstalled context + tests

src/shared/pages/welcomePage/browserList.js
This patch uses the existing firefox hotkey list populator when switching browsers instead of manually replacing the browser name.
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468934628
=> Code Review: Better firefox hotkey replacement

src/chromium/interfaces/contextMenus.js, src/chromium/interfaces/launchBrowser.js, src/chromium/interfaces/listeners.js, src/firefox/interfaces/launchBrowser.js, src/firefox/interfaces/listeners.js, src/shared/backgroundScripts/contextMenus.js, src/shared/backgroundScripts/hotkeys.js, src/shared/backgroundScripts/listeners.js, src/shared/backgroundScripts/validTab.js, test/chromium/interfaces/contextMenus.test.js, test/chromium/interfaces/launchBrowser.test.js, test/firefox/interfaces/launchBrowser.test.js, test/setup.test.js, test/shared/backgroundScripts/contextMenus.test.js
This patch changes launchBrowser and its callers to use url as a parameter instead of tab and retrieve the current tab ID in the function itself.
The calls to launchBrowser and telemetry in the context menu handler functions are quite repetitive. Since the url parameter doesn't change, it might be worth condensing them.
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468904714
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468671493
=> Code Review: Use url parameter instead of tab

src/shared/backgroundScripts/contextMenus.js, src/shared/backgroundScripts/listeners.js, test/shared/backgroundScripts/contextMenus.test.js
On install, ensure that the welcome page is only opened on first install of the extension. Update the icon on startup instead of just on install.
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468672447
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468908113
=> Code Review: changes to startup listener

src/firefox/api.js, src/shared/pages/welcomePage/browserList.js
Removes `_isValidHandlerApp` and uses `_isValidHandlerExecutable` solely. Remove the logs object in the api.
Code review comments:
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468882694
=> Code Review: use firefox source for api logs & condense redundant function

src/chromium/interfaces/contextMenus.js, src/shared/backgroundScripts/contextMenus.js, test/chromium/interfaces/contextMenus.test.js, test/shared/backgroundScripts/contextMenus.test.js
Change tab.url to info.pageUrl for the page context menus. Also rename such contexts for more clarity.
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468670953
=> Code review: pageUrl usage

src/chromium/interfaces/contextMenus.js, src/shared/backgroundScripts/contextMenus.js, test/chromium/interfaces/contextMenus.test.js
Adds await to each create call. Opted for this method over updating async attributes later for ease of implementation and readability. Also moved a separator to chromium specific action menu to avoid duplicate ones in firefox.
Code review comments:
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468672268
=> Make context menu init sync

metrics.yaml, src/chromium/interfaces/contextMenus.js, src/chromium/interfaces/listeners.js, src/firefox/interfaces/listeners.js, src/firefox/manifest.json, src/shared/backgroundScripts/contextMenus.js, src/shared/backgroundScripts/hotkeys.js, src/shared/backgroundScripts/telemetry.js, src/shared/pages/welcomePage/browserList.js, src/shared/pages/welcomePage/script.js, test/shared/backgroundScripts/telemetry.test.js
Use the glean API directly in each file. As per the [glean docs](https://mozilla.github.io/glean/book/user/pings/sent-by-glean.html), the pings set up will default to use events or metrics and be sent automatically with no input from me. This, however, means that you cannot see the specific ping info of the logs in the console using the glean API ([seen here](https://mozilla.github.io/glean/book/user/debugging/javascript.html)), but you can still see that the pings were sent. 
Everything to do with glean will get a data and code review in the future.
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468913786
=> Code Review: telemetry pings no longer use storage api

src/shared/pages/welcomePage/localization.js, src/shared/pages/welcomePage/script.js
This patch safely replaces links in the localized text. With this change brought the required changes to the shortcuts page redirecting as well, making it a special case. 
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468665507
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468662523
- https://github.com/mozilla/firefox-launch/pull/18/files#r1468660631
=> Code Review: welcome page links

metrics.yaml, package-lock.json, package.json, src/shared/backgroundScripts/telemetry.js, test/setup.test.js
Uses UAParser library to get telemetry information from the useragent. Adds the remaining fields required by the spec.
=> Add UA parsing for telemetry

src/chromium/interfaces/listeners.js, src/shared/backgroundScripts/getters.js
Fixes #58 
When the default browser was changed from Firefox to Firefox Private Browsing and then the extension was reloaded, there would be a call to, on install, set the default browser back to Firefox.  This was here from some older code, but serves no purpose as on a call to `getExternalBrowser()` (the only time we retrieve this data), if there is no existing data, the function creates it. 
Similar story for `getIsFirefoxInstalled()`, there is no need to call it there as the function itself already handles the empty case.
=> Prevent external browser reset on install events

metrics.yaml, src/shared/backgroundScripts/telemetry.js, test/shared/backgroundScripts/telemetry.test.js
As it turns out, not every field in the `client_info` ping is modifiable. See [the config parameter of Glean.initialize()](https://mozilla.github.io/glean.js/functions/core_glean.default.initialize.html). Thus, the custom OS name and version were not being reported in the initialization. To report them properly, add these fields to the startup event.
The spec has also changed, with lots of fields shared between the install event and startup event being directed to just the startup event. So much so that, with the initialization of `client_info` and the startup pings, there is no more need for an install event. See the [install telemetry section of the spec](https://docs.google.com/document/d/1jTxG4kyDsgwAVHYkDvHvABmO85-wk9vppJe6ikNe76A/edit#heading=h.2fmwmhfme6rn), the extension version …
=> OS name/version ping fix, redundant pings removed

metrics.yaml, src/chromium/interfaces/getters.js, src/chromium/interfaces/launchBrowser.js, src/chromium/interfaces/listeners.js, src/chromium/manifest.json, src/firefox/interfaces/getters.js, src/shared/pages/welcomePage/localization.js, src/shared/pages/welcomePage/script.js, test/chromium/interfaces/getters.test.js, test/chromium/interfaces/launchBrowser.test.js, test/setup.test.js
Fixes #79 
Fixes #54 
Fixes #50 
[Native Messaging document](https://docs.google.com/document/d/1I1WY5lV62zDy86CCceBXdQm-4PL18VKvXy8p6UmuA7g/edit)
This patch has 2 related changes. First, `isFirefoxInstalled()` is replaced by `getInstalledFirefoxVariant()` which uses native messaging to determine which firefox variant of Dev, Nightly, Release, ESR, is installed in that order with an early return if so. The return value is the native messaging host name to be used within `launchBrowser()`. This is where the extension commands the variant of firefox to open the url in normal or private mode.
=> Native Messaging to launch Firefox and check if Firefox is installed

src/_locales/en/messages.json
- Added comments not to translate Firefox Bridge whenever it appears in a string.
- It seems like `Private window` should either be `Private Window` or `private window`, so suggested the former.
=> L10n comment and string suggestions

metrics.yaml, src/chromium/interfaces/getters.js, src/firefox/api.js, src/firefox/interfaces/getters.js, src/firefox/schema.json, src/shared/backgroundScripts/listeners.js, src/shared/backgroundScripts/telemetry.js, test/chromium/interfaces/getters.test.js, test/chromium/interfaces/launchBrowser.test.js, test/firefox/interfaces/getters.test.js, test/firefox/interfaces/launchBrowser.test.js, test/setup.test.js
For the firefox extension:
- Accesses the preference `browser.firefoxbridge.installId` to get the generated ID from Firefox
- Submits this ID along with the glean ID whenever telemetry is turned on
For the chromium extension:
- Calls the native messaging host and requests the installId
- Submits this along with the glean ID whenever telemetry is turned on
The actual implementation for generating the ID in firefox is not yet complete.
[InstallID Spec](https://docs.google.com/document/d/1coIruhHHIADfb1fdD8PY_w3urZ7YIKp85lURNfGxoKE/edit#heading=h.5z4a4v590jeu)
[InstallID bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1887209)
=> Link telemetry between extensions and Firefox

.github/CODEOWNERS
Revise CODEOWNERS to point to individual users until a team can be made within mozilla-extensions.
=> Update CODEOWNERS to temporarily point to individuals

metrics.yaml, pings.yaml, src/_locales/en/messages.json, src/chromium/manifest.json, src/firefox/manifest.json, src/shared/pages/welcomePage/index.html, src/shared/pages/welcomePage/localization.js
Fixes #93 
This patch changes some welcome page strings, localizes shortcut strings, and updates the glean contact info in metrics.yaml. pings.yaml is required by the gleanjs builder but is not used since all pings are being sent in event pings, so it is commented out.
=> Welcome page string changes + glean link and email finalizing.

src/_locales/en/messages.json, src/chromium/interfaces/contextMenus.js, src/shared/backgroundScripts/contextMenus.js, test/chromium/interfaces/contextMenus.test.js, test/shared/backgroundScripts/contextMenus.test.js
This is the final result in both extensions.
To do this within the chrome extension, some re-ordering had to occur to make room for the 6 item limit within the context menu. The separator counts as 1 item.
=> Add feedback action menu item, split the dynamic chrome action item into two constant ones.

src/chromium/manifest.json, src/firefox/manifest.json
This is Greg Sherman's change to removed unused permissions, which Chrome Web Store does not allow.
=> Remove unused permissions in manifest files

src/_locales/en/messages.json, src/shared/pages/welcomePage/index.html, src/shared/pages/welcomePage/localization.js, src/shared/pages/welcomePage/style.css
Added privacy policy and moved telemetry toggle to the bottom of the welcome page.
There were some issues with adding new lines to the welcome page within the same `data-locale` tag which seem to be preexisting. For now I've made the Privacy Policy three separate pararaphs.
=> Added privacy policy to extension welcome page

README.md, package-lock.json, package.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1894635 for why Python 3.12 does not work well with Glean. It was fixed but we're stuck on Glean.js v2.0.5 since newer versions don't work with webextensions anymore apparently 🤷
=> Update glean.js and force python 3.11 to be used
